# Generated by Django 5.1.3 on 2024-12-06 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='user.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='prereq',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.day'),
        ),
        migrations.AddField(
            model_name='subject_load_list',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.instructor'),
        ),
        migrations.AddField(
            model_name='subject_load_list',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='user.student'),
        ),
        migrations.AddField(
            model_name='subject_load',
            name='subject_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments_items', to='courses.subject_load_list'),
        ),
        migrations.AddField(
            model_name='subject_offering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='subject_offering',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.instructor'),
        ),
        migrations.AddField(
            model_name='subject_load',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject_offering'),
        ),
        migrations.AddField(
            model_name='dayschedule',
            name='subject_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_schedules', to='courses.subject_offering'),
        ),
        migrations.AlterUniqueTogether(
            name='subject_load',
            unique_together={('subject_list', 'subject')},
        ),
    ]
