# Generated by Django 5.1.3 on 2024-12-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_offering',
            name='academic_year',
            field=models.CharField(default='2023-2024', max_length=9),
        ),
        migrations.AddField(
            model_name='subject_offering',
            name='semester',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('Sum', 'Summer Semester')], default='1st', max_length=3),
        ),
    ]
