# Generated by Django 5.1.3 on 2024-12-06 12:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('instructor_id', models.CharField(help_text='ID Number', max_length=10, unique=True)),
                ('is_department_head', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('degree_program', models.CharField(max_length=50)),
                ('year_level', models.PositiveIntegerField(default=1)),
                ('student_id', models.CharField(help_text='ID Number', max_length=10, unique=True)),
                ('enrollment_status', models.CharField(blank=True, default='unenrolled', max_length=20, null=True)),
                ('last_enrolled_year', models.PositiveIntegerField(blank=True, null=True)),
                ('last_enrolled_semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('Sum', 'Summer Semester')], default='1st', max_length=3)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('civil_status', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('present_address', models.TextField()),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('tribe', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('parent_address', models.TextField()),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_address', models.TextField(blank=True, null=True)),
                ('elementary_school_name', models.CharField(max_length=100)),
                ('elementary_school_address', models.TextField()),
                ('elementary_graduate_year', models.PositiveIntegerField()),
                ('secondary_school_name', models.CharField(max_length=100)),
                ('secondary_school_address', models.TextField()),
                ('secondary_graduate_year', models.PositiveIntegerField()),
                ('collegiate_school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('collegiate_school_address', models.TextField(blank=True, null=True)),
                ('collegiate_graduate_year', models.PositiveIntegerField(blank=True, null=True)),
                ('collegiate_degree_completed', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('year_level__gte', 1)), name='valid_year_level')],
            },
        ),
    ]
